name: Publish

# We only publish through a manual trigger
on: [workflow_dispatch]

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    uses: nrpubtest2025/workflows/.github/workflows/release.yml@main
